### ISSUE TITLE
Continue has migrated to using config.json instead of config.py

### ISSUE THREAD

**Issue by philippthiele** [nistvan86/continuedev-llamacpp-gpu-llm-server#1]
I wanted to setup according to the description in the Readme, but I am unable to as I do not know what to put in the config.json. 

Here are the migration docs, that do not really help me: https://github.com/continuedev/continue/blob/main/docs/docs/config-file-migration.md

Maybe you have an idea how to solve the issue. Thank you in advance!

**Comment by nistvan86** [comment]
Hi.

I haven't used this setup for a while, so I was unaware of the changes.
I think it should work with the "OpenAI-compatible API" section, as llama-cpp provides an OpenAI API emulation.
I'm not sure what the "model" property will be, I think it's the model file name without the extension: `phind-codellama-34b-v2.Q4_K_M` or `phind-codellama-34b-v2`

**Comment by philippthiele** [comment]
So I got it to run with the openai-aiohttp provider, but I didn't manage to let it run on my GPU instead of CPU.

What is much easier is using ollama with WSL2 and docker:
- install CUDA on windows: https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
- install CUDA in WSL: https://[developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_network](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_network)
- Use the NVidia GPU guide in the docker container repo of ollama: https://hub.docker.com/r/ollama/ollama
- run models with e.g.:
  - docker exec -it ollama ollama run codellama:7b
  - docker exec -it ollama ollama run codellama:13b
  - docker exec -it ollama ollama run codellama:34b
- use model definition accordingly, e.g.:
```
  "models": [    
    {
      "title": "Code Llama",
      "provider": "ollama",
      "model": "codellama-13b"
    }
  ],
```

**Comment by nistvan86** [comment]
I was about to add to my last comment yesterday that you should probably try to use Ollama because it seems much better integrated with continue.dev and makes the modell instantiation much easier. But I didn't had any real life experience with it.

So I'm actually thankful you tested and written down your the steps! :)

I'm going to link this post in the top of the readme, so newcomers will find it first.
